package MatriculasApp;


/**
* MatriculasApp/MatriculasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatriculasApp.idl
* martes 7 de abril de 2020 11H43' CEST
*/

public interface MatriculasOperations 
{
  String findTxtAndDelete ();
  void shutdown ();
} // interface MatriculasOperations
