package MatriculasApp;


/**
* MatriculasApp/MatriculasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatriculasApp.idl
* martes 17 de marzo de 2020 18H14' CET
*/

public interface MatriculasOperations 
{
  String findTxtAndDelete ();
  void shutdown ();
} // interface MatriculasOperations
