package MatriculasApp;


/**
* MatriculasApp/Matriculas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatriculasApp.idl
* martes 14 de abril de 2020 19H04' CEST
*/

public interface Matriculas extends MatriculasOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Matriculas
