package MatriculasApp;


/**
* MatriculasApp/MatriculasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatriculasApp.idl
* miércoles 8 de abril de 2020 18H53' CEST
*/

public interface MatriculasOperations 
{
  String matriculasDetectorIn ();
  void shutdown ();
} // interface MatriculasOperations
