package MatriculasApp;


/**
* MatriculasApp/MatriculasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatriculasApp.idl
* sábado 11 de abril de 2020 11H08' CEST
*/

public interface MatriculasOperations 
{
  String matriculasDetectorIn ();
  String matriculasDetectorOut ();
  void shutdown ();
} // interface MatriculasOperations
