package MatriculasApp;


/**
* MatriculasApp/MatriculasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatriculasApp.idl
* domingo 15 de marzo de 2020 12H17' CET
*/

public interface MatriculasOperations 
{
  String readMatriculas ();
  void shutdown ();
} // interface MatriculasOperations
