package MatriculasApp;

/**
* MatriculasApp/MatriculasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatriculasApp.idl
* domingo 15 de marzo de 2020 12H17' CET
*/

public final class MatriculasHolder implements org.omg.CORBA.portable.Streamable
{
  public MatriculasApp.Matriculas value = null;

  public MatriculasHolder ()
  {
  }

  public MatriculasHolder (MatriculasApp.Matriculas initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MatriculasApp.MatriculasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MatriculasApp.MatriculasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MatriculasApp.MatriculasHelper.type ();
  }

}
