package MatriculasApp;


/**
* MatriculasApp/Matriculas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatriculasApp.idl
* domingo 15 de marzo de 2020 11H37' CET
*/

public interface Matriculas extends MatriculasOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Matriculas
